# Generated by Django 4.2.4 on 2023-10-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('founde', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycustomusers',
            old_name='is_myuser',
            new_name='is_lostuser',
        ),
    ]
