# Generated by Django 4.2.4 on 2023-10-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founde', '0004_biddingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
